services:
  # üêò Base de Dados Principal (PostgreSQL)
  postgres:
    image: postgres:16-alpine
    container_name: nexus_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      # Criamos m√∫ltiplas DBs num s√≥ container para poupar mem√≥ria
      POSTGRES_MULTIPLE_DATABASES: "booking_db,property_db,user_db,sync_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Script m√°gico para criar as 4 BDs no arranque
      - ./postgres/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # üê∞ RabbitMQ (Mensageria)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: nexus_rabbitmq
    ports:
      - "5672:5672" # Porta do protocolo AMQP (Java usa esta)
      - "15672:15672" # Porta do Painel de Controlo Web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
