name: Backend CI
# Corre todos os testes dos modulos.
# Booking, User, Property, Api-Gateway e Sync
on:
  push:
    paths:
      - 'backend/**' # Só dispara se houver alterações no backend
  pull_request:
    paths:
      - 'backend/**'

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'maven' # Cache inteligente para acelerar builds futuros

      - name: Install Dependencies
        working-directory: ./backend
        run: mvn clean install -DskipTests
        # Compila e instala todos os módulos (incluindo common-library) no repositório local
        # sem correr os testes ainda, garantindo que as dependências existem.

      - name: Run Tests
        working-directory: ./backend
        run: mvn test
        # Agora corre os testes de todos os módulos.